const API_BASE = ""; let selectedStyle = "IEEE"; let selectedFile = null; const $ = id => document.getElementById(id); const fileInput = $("fileInput"); const dropzone = $("dropzone");
function formatBytes(bytes){if(!bytes)return"0 B";const units=["B","KB","MB","GB"],i=Math.floor(Math.log(bytes)/Math.log(1024));return (bytes/Math.pow(1024,i)).toFixed(i?1:0)+" "+units[i]}
function setFile(file){if(!file)return;if(!file.name.toLowerCase().endsWith(".docx")){showError("Please select a DOCX manuscript.");return}selectedFile=file;$("fileTitle").textContent="Manuscript selected";$("fileMeta").textContent="Ready to analyse and format";$("selectedName").textContent=file.name;$("selectedSize").textContent=formatBytes(file.size);$("selectedFile").classList.remove("hidden");$("errorMessage").classList.add("hidden")}
function showError(message){$("errorMessage").textContent=message;$("errorMessage").classList.remove("hidden")}
fileInput.addEventListener("change",e=>setFile(e.target.files[0]));$("clearFile").addEventListener("click",()=>{selectedFile=null;fileInput.value="";$("selectedFile").classList.add("hidden");$("fileTitle").textContent="Drop your manuscript here";$("fileMeta").textContent="or click to browse from your computer"});
["dragenter","dragover"].forEach(event=>dropzone.addEventListener(event,e=>{e.preventDefault();dropzone.classList.add("dragging")}));["dragleave","drop"].forEach(event=>dropzone.addEventListener(event,e=>{e.preventDefault();dropzone.classList.remove("dragging")}));dropzone.addEventListener("drop",e=>setFile(e.dataTransfer.files[0]));
document.querySelectorAll(".style-card").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll(".style-card").forEach(b=>b.classList.remove("selected"));button.classList.add("selected");selectedStyle=button.dataset.style;$("activeStyle").textContent=selectedStyle}));
async function processManuscript(){if(!selectedFile)return showError("Upload a DOCX manuscript first.");const button=$("processButton"),format=$("outputFormat").value,form=new FormData();form.append("file",selectedFile);form.append("style",selectedStyle);form.append("output_format",format);button.disabled=true;button.textContent="Analysing manuscript…";$("resultState").textContent="PROCESSING";$("progressBar").style.width="65%";$("resultMessage").textContent="ManuScript is analysing structure and applying the selected format.";try{const response=await fetch(API_BASE+"/process",{method:"POST",body:form});if(!response.ok)throw new Error(await response.text()||"Processing failed.");const data=await response.json(),stats=data.stats||{};$("wordCount").textContent=stats.word_count??"—";$("readability").textContent=stats.readability_score??"—";$("progressBar").style.width="100%";$("resultState").textContent="COMPLETE";$("resultMessage").textContent="Formatting completed successfully.";if(data.download_url){const link=$("downloadButton");link.href=data.download_url;link.classList.remove("disabled")}const insights=data.quality_report||[];$("insights").innerHTML=insights.length?insights.slice(0,6).map(item=>'<div class="insight"><strong>'+escapeHtml(item.rule||"Quality check")+'</strong><p>'+escapeHtml(item.message||"Check completed.")+"</p></div>").join(""):'<div class="empty-state">No additional quality warnings were returned.</div>';loadDocuments()}catch(error){$("resultState").textContent="ERROR";$("progressBar").style.width="0";showError(error.message||"Could not connect to the processing service.");$("resultMessage").textContent="The manuscript could not be processed."}finally{button.disabled=false;button.innerHTML="Format manuscript <span>→</span>"}}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char]))}
async function loadDocuments(){const list=$("documentsList");try{const response=await fetch(API_BASE+"/documents");if(!response.ok)throw new Error();const data=await response.json(),docs=Array.isArray(data)?data:(data.documents||[]);list.innerHTML=docs.length?docs.slice(0,8).map(doc=>'<div class="document"><div><strong>'+escapeHtml(doc.filename||doc.name||"Untitled document")+'</strong><span>'+escapeHtml(doc.created_at||doc.date||"Processed document")+'</span></div><span class="doc-tag">'+escapeHtml(doc.style||"FORMATTED")+"</span></div>").join(""):'<div class="empty-state">No recent documents.</div>'}catch{list.innerHTML='<div class="empty-state">Document history will appear when the backend is connected.</div>'}}
$("processButton").addEventListener("click",processManuscript);$("refreshDocuments").addEventListener("click",loadDocuments);$("themeToggle").addEventListener("click",()=>document.documentElement.classList.toggle("light"));loadDocuments();